services:
  ph-municipalities:
    container_name: ph-municipalities
    image: ciatph/ph-municipalities:dev
    env_file:
      - ./app/.env
    build:
      context: ./app
      dockerfile: Dockerfile
      target: development
    networks:
      - ph-municipalities
    volumes:
      - ./app:/opt/app
      - ./scripts:/opt/app/scripts
      - ./docs/diagrams:/opt/app/diagrams
      - ./README.md:/opt/app/README.tmp
      - /opt/app/node_modules
    ports:
      - "9229:9229"
    stdin_open: true
    tty: true

networks:
  ph-municipalities:
    name: ph-municipalities
    external: false
