name: Lint and Test

on:
  push:
    branches-ignore:
      - 'master'

jobs:
  lint-app:
    name: Lint App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Use NodeJS v16.14.2
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.2
      - name: Install Dependencies and lint
        run: |
          cd app
          npm install
          npm run lint

  test:
    name: Test App
    runs-on: ubuntu-latest
    needs: lint-app
    env:
      EXCEL_FILE_URL: ${{ secrets.EXCEL_FILE_URL }}
      SHEETJS_COLUMN: ${{ secrets.SHEETJS_COLUMN }}
      SORT_ALPHABETICAL: ${{ secrets.SORT_ALPHABETICAL }}
      SPECIAL_CHARACTERS: ${{ secrets.SPECIAL_CHARACTERS }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Use NodeJS v16.14.2
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.2
      - name: Install Dependencies and Test
        run: |
          cd app
          npm install
          npm test
